name: CI
on:
  push:
    branches: [master]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.5.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2  
        with:
          node-version: 18
        
      - name: Install Dependencies
        run: npm ci
        
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
        
      - name: Start PostgreSQL Server
        run: |
          sudo /etc/init.d/postgresql start
          sudo service postgresql start
        
      - name: Run Database Setup Script
        run: bash ${{ github.workspace }}/setup-test-db.sh
        
      - name: Run Tests
        run: npm test
        
      - name: Upload test coverage
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_coverage
          path: coverage

      - name: Check Test Results
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Tests failed. Ignoring push request."
            exit 1
          fi
