name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: format-code-and-check-bugs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --write .

      - name: Run ESLint
        run: npx eslint . --format=node_modules/eslint-html-reporter/reporter.js --output-file=eslint-report.html
        
      - name: Upload lint report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: eslint-report.html
          path: eslint-report.html

  tests:
    needs: lint
    name: run-all-tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Start PostgreSQL Server
        run: |
          sudo /etc/init.d/postgresql start
          sudo service postgresql start

      - name: Run Database Setup Script
        run: bash ${{ github.workspace }}/setup-test-db.sh

      - name: Install and Start Redis Server
        run: |
          curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
          sudo apt-get update
          sudo apt-get install redis
          redis-server --daemonize yes

      - name: Run Tests
        run: npm test

      - name: Upload test coverage
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_coverage
          path: coverage
